import { Callout } from "@/components/ui/Callout";
import { KeyTerms } from "@/components/ui/KeyTerms";
import { StepCards } from "@/components/ui/StepCards";
import { CodeBlock } from "@/components/code/CodeBlock";
import { LessonHeader } from "@/components/ui/LessonHeader";

export default function MessagesRolesPage() {
  const codeEx = `
[
  { 
    "role": "system", 
    "content": "You are a helpful pirate assistant." 
  },
  { 
    "role": "user", 
    "content": "Where can I find the best pizza in New York?" 
  },
  { 
    "role": "assistant", 
    "content": "Arrr matey! The best slice of pie be..." 
  }
]
  `;

  return (
    <>
      <LessonHeader 
        title="Messages & Roles" 
        subtitle="LLMs are stateless — they forget everything instantly. To have a conversation, you must send the entire transcript back every time using a structured list of roles." 
      />

      <Callout icon="🧠" className="bg-[#f0f9ff] border-[#bae6fd] [&>div:last-child]:text-[#0369a1]">
        <strong>No Short-Term Memory:</strong> <br/>
        Every single API call is like meeting the AI for the very first time. 
        The only way it knows what you said earlier is if you include it in the <strong>Transcript</strong>.
      </Callout>

      <h2>The Three Roles</h2>
      <p>
        The API identifies who is speaking using three distinct <code>Roles</code>. 
        This JSON structure is the industry standard format:
      </p>

      <CodeBlock 
        code={codeEx} 
        language="json" 
        filename="messages.json" 
      />

      <StepCards 
        steps={[
          { icon: "🎨", title: "System", description: "The 'Director'. Defines the AI's persona, expertise, and rules." },
          { icon: "🧑", title: "User", description: "The 'Customer'. The human providing instructions or questions." },
          { icon: "🤖", title: "Assistant", description: "The 'Actor'. The previous replies generated by the AI." },
        ]}
      />

      <Callout icon="⭐" className="bg-[#f3e8ff] border-[#e9d5ff] [&>div:last-child]:text-[#7e22ce]">
        <strong>Pro Developer Tip:</strong> <br/>
        Use the <strong>System Role</strong> to force the AI into specific formats like JSON or 
        to block it from answering off-topic questions.
      </Callout>

      <KeyTerms 
        terms={[
          { name: "Transcript", definition: "A full list of past messages sent in the context window.", color: "#8b5cf6" },
          { name: "Persona", definition: "The specific personality defined in the system prompt.", color: "#10b981" },
          { name: "Chat Completion", definition: "The technical name for getting a response from a conversation.", color: "#3b82f6" },
        ]}
      />
    </>
  );
}
